### PR TITLE
[WIP] Backend for Central Controller (part 3)

### PR DESCRIPTION
**Pull request by wvlothuizen**
somehow the relation between the main repo and the prior fork was lost, which closed the PR (#219). This is a new attempt

### CODE REVIEW

**Comment by wvlothuizen** [comment]
@imranashraf 
Hi Imran, I finally got to merging branch develop back in here, and think this would be a great time to review and merge this PR. 
The CC backend has come to a stage where the it passes most all OpenQL tests in https://github.com/DiCarloLab-Delft/PycQED_py3, as well as the tests here of course.

**Comment by imranashraf** [comment]
@wvlothuizen this is a big PR in which you are doing so many things. can you please provide a high-level summary of the things you have done, especially for the files which are not related to CC?

**Comment by wvlothuizen** [comment]
@imranashraf sure, here we go. The comments below are based on looking at the output of 'diff -w develop' from branch 'feature/cc'

Generic:
- partly split .h files into .h and .cc, and built a library for the .cc files. NB: requires 'inline' attribute on quite some functions that remain in .h files
- put unused code between ifdefs (so it can be fully removed later on)
- none of the changes should affect existing interfaces or functionality

platform.h:
- moved implementation to new file platform.cc
- diff between develop:platform.h and feature/cc:platform.cc shows  no material changes

program.h:
- moved implementation to new file program.cc
- diff between develop:program.h and feature/cc:program.cc shows no material changes

compile_options.h:
- new file introduced to allow deprecating dead code

arch/cc_light/cc_light_eqasm_compiler.h:
- included <compile_options.h> 

arch/cc_light/cc_light_scheduler.h:
- made functions 'inline' to support creating a library for .cc files

instruction_map.h:
- made load_instructions() inline
- added compile option OPT_USED_HARDWARE to disable unused code

ir.h:
- made functions qasm() and write_qasm() inline

str.h:
- made function int_to_str() inline

utils.h:
- made functions inline
- added macro JSON_ASSERT to improve error handling on non-existing JSON keys (used by CC backend)


circuit.h:
- made functions 'inline'
- moved in functions split_circuit(circuit &x), contains_measurements(circuit &x), contains_unoptimizable_gates(circuit &x) from kernel.h

kernel.h:
- changed occurrences of 'std::map<std::string,custom_gate*>' into already existing instruction_map_t
- changed identifier 'gate_definition' into 'instruction_map'
- added check whether parameters of parameterized instruction actually exist
- moved out functions split_circuit(circuit &x), contains_measurements(circuit &x), contains_unoptimizable_gates(circuit &x) to circuit.h because they don't use class quantum_kernel, but do use (typedef) circuit
- moved class definition and some functions from bottom to top of file

openql.h:
- added deprecation option OPT_TARGET_PLATFORM
- cleanup of unused code

options.h:
- added option for CC backend
- made functions inline

classical.h:
- improved error handling if running out of classical registers

gate.h:
- added compile options OPT_UNFINISHED_OPTIMIZATION and OPT_USED_HARDWARE to disable unused code

hardware_configuration.h:
- changed some 'json &' into 'const json &'


qasm_loader.cc:
- moved to subdirectory 'attic' because it is unused

exception.{h,cc}:
- no longer '#include "exception.cc"' in exception.h, but have prover separation

swig/CMakeLists.txt:
- build library for .cc files

**Comment by imranashraf** [comment]
@wvlothuizen looks good, merging.

**Pull request merged**
