### PR TITLE
Feature/cqasm reader

### PR DESCRIPTION
**Pull request by QFer**
* Added cqasm reader interface (python and C++)
* Added tests for python and C++
* Integrated to develop branch
* Added/adjusted installation.rst
* Solved bug in clifford.h that appeared during testing
* Resolved some of the many warnings when compiling OpenQL

### CODE REVIEW

**Comment by imranashraf** [comment]
Merge develop branch to your work to resolve any possible issues.
secondly, CI should also pass

**Comment by imranashraf** [comment]
@QFer thanks for the contribution. some points:
- cannot build on my linux machine, CI is also failing. make sure we do not break the builds on all the 3 OSes. 
- C++ tests are redundant, I will suggest removing them

**Comment by QFer** [comment]
@imranashraf  Hi Imran, do you mean removing the file: test_cqasm_reader.cc at all and leaving the python tests in?
The builds fails because I try to load libQasm as a submodule but Travis doesn't have the credentials to get the repository. I then tried to point to the fork https://github.com/imranashraf/travis-libqasm.git. Do you think this is a good solution. Please have a look at https://docs.travis-ci.com/user/private-dependencies/

**Comment by imranashraf** [comment]
@QFer yes, only leave python tests. 

Please use https://github.com/QE-Lab/libqasm. it is a public repo, so should not be an issue. The https://github.com/imranashraf/travis-libqasm.git is my temporary testing which i used when setting up Travis CI for openql to avoid unncessary pushes to the main repo.

**Comment by QFer** [comment]
@imranashraf Oke I will change the repo. Currently we pass all the tests. I'm happy with that. I will make a new commit with your request later today

**Comment by jvansomeren** [comment]
Hi Fer and Imran,

I saw the discussion on removing the C++ test.
I am wondering why you consider it redundant.
Testing of functionality is redundant but testing that the interface works in C++ is not.

Best,

Hans

Op 1 apr. 2020, om 16:51 heeft Imran Ashraf <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


  *   C++ tests are redundant, I will suggest removing them

**Comment by QFer** [comment]
@jvansomeren @imranashraf You have a point Hans. You two decide. I'm happy to move it back in. Just let me know.

**Comment by jvansomeren** [comment]
Does the working of the python interface by means of swig guarantee the working of the c++ interface?

Groet,

Hans van Someren

atelier GROENBLAUW
Koningsplein 93<x-apple-data-detectors://1/0>
2611 XG Delft<x-apple-data-detectors://1/0>
06 4298 2220<tel:06%204298%202220>

hans@ateliergroenblauw.nl<mailto:hans@ateliergroenblauw.nl>

www.ateliergroenblauw.nl<http://www.ateliergroenblauw.nl/>
www.groenblauwenetwerken.com<http://www.groenblauwenetwerken.com/>
www.huisjeboompjebeter.nl<http://www.huisjeboompjebeter.nl/>





Op 8 apr. 2020 om 19:41 heeft QFer <notifications@github.com> het volgende geschreven:

﻿

@jvansomeren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jvansomeren&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=Fx3Xpa4akddPvCmMYBuzwN9ZZeTvgVR8QA4dKI_vt58&s=_-1GdcUdYfNRvlJ8LLPENef6SqzHIeR0xsIXg5TdQXI&e=> @imranashraf<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_imranashraf&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=Fx3Xpa4akddPvCmMYBuzwN9ZZeTvgVR8QA4dKI_vt58&s=I_-lBDA1hRAiUgrCCJSjFJnjM6UBF5297Tu5z_oDzuc&e=> You have a point Hans. You two decide. I'm happy to move it back in. Just let me know.

**Comment by imranashraf** [comment]
@jvansomeren there are multiple reasons for it:
- including C++ tests increases build time and they are basically testing the same functionality which is being tested by python tests, so they are redundant
- C++ tests are not part of CI, so there are higher chances that they will soon be out of sync unnoticed

**Pull request merged**
