### PR TITLE
Backend for Central Controller (part 4)

### PR DESCRIPTION
**Pull request by wvlothuizen**
This PR provides:
- update to CC backend to support changed semantics of the CC's 'seq_bar' instruction
- conversion of CC documentation to Sphinx .RST format
- additions to CC documentation
- compiler options that disable unused code (options and code needs to be removed in the future)

### CODE REVIEW

**Comment by wvlothuizen** [comment]
@imranashraf this build fails, as far as I can see while executing:
`+ python3 libqasm/qasm_flex_bison/setup.py install
`
Has anything been recently changed to libqasm, or the CI configuration in branch develop?

**Comment by imranashraf** [comment]
i just tested on on my system and both libqasm and openql build fine. IMHO nothing changed regarding CI configuration. Recently, I cannot see the CI build log as browser is giving warning.

**Comment by wvlothuizen** [comment]
@imranashraf would you like to review this PR?

**Comment by wvlothuizen** [comment]
@imranashraf can you review and merge this PR?

I fixed the build problems introduced by merging with PR #293. Some tests still fail, see attachment, but that does not seem to be caused by this PR

[log.txt](https://github.com/QE-Lab/OpenQL/files/4298400/log.txt)

**Comment by imranashraf** [comment]
@wvlothuizen I will have a look at it tomorrow morning.

**Comment by imranashraf** [comment]
failing tests are un-related. merging.

**Pull request merged**
