### PR TITLE
Add documentation file for the visualizer

### PR DESCRIPTION
**Pull request by tmeer**
Added a rough draft for the documentation of the visualizer, explaining its usage.

Also contains a restructuring of the code that handles positioning elements on the image.

### CODE REVIEW

**Comment by jvanstraten** [comment]
To make the visualizer page appear on readthedocs you'll have to add it to the index file. Otherwise I see no immediate problems as long as the docs compile, but I didn't check extensively yet.

**Comment by tmeer** [comment]
> 
> 
> To make the visualizer page appear on readthedocs you'll have to add it to the index file. Otherwise I see no immediate problems as long as the docs compile, but I didn't check extensively yet.

Added it to the index file.

**Comment by jvanstraten** [comment]
Checking a bit more thoroughly now that I have my dev environment open; make sure to run `make html` in the docs folder to ensure everything works by the way (you'll need to install sphinx using pip3 and maybe some other packages if it complains, but it shouldn't give you any trouble otherwise). Among many other things from other people who apparently did not do this or ignore the output, you'll find

```
.../docs/visualizer.rst:139: WARNING: Could not lex literal_block as "json". Highlighting skipped.
```

because you can't open a JSON block with an object entry; you need {} around the whole thing to make it work.

I thought these PRs were going into develop though? Going through a separate branch on the main OpenQL repo before going to develop seems redundant to me, but whatever.

Entirely unrelated, I sent you an e-mail earlier this week asking for a picture of you to put in the slides for the Intel review presentation. I'm not sure you saw? (Or maybe I used the wrong address?) I have everyone else's pictures already, so it's the only thing I have left to do to finish my slides.

**Comment by tmeer** [comment]
I get a giant list of errors when I try to generate the docs (I suppose from missing other packages, I'll fix that later), but if the above is the only warning the visualizer doc file gives on your properly set up environment, that warning should be fixed now.

Your e-mail slipped my mind, I'll message you today.

**Review by jvanstraten — APPROVED** [review]
Looks good to me. I also don't see a reason to delay this until more people have looked at it since it doesn't go into develop, so I'll merge. Once the eventual PR into develop appears, Hans and Razvan will probably want to have a closer look as well.

**Pull request merged**
