### PR TITLE
Remove sweep points functionality

### PR DESCRIPTION
**Pull request by pablolh**
- Cleanup sweep points-related API functions
- Cleanup tests and examples

### CODE REVIEW

**Comment by pablolh** [comment]
@wvlothuizen This removes the deprecated sweep points feature, as per your email from Friday.

**Comment by wvlothuizen** [comment]
OK! I approved running CI (which must be done once for new users), and see some failures.

We have a sort of convention to prefix the PR title with "[WIP]" until its ready for review (because you need write access to set it to 'Draft' o GitHub), and then ask for a review from ~2 people when done

**Comment by pablolh** [comment]
Sorry for the failed CI, it should be fixed now.
I'm relatively unfamiliar with Github's interface, I don't see where I can add reviewers or assignees.
CI still doesn't seem to have started on the 2nd push.

**Review by wvlothuizen — CHANGES_REQUESTED** [review]
A nice cleanup, looks good and seems to cover all uses of sweep_points.

One note: also update CHANGELOG.md, then I'd approve (but maybe Hans also likes to chime in)

**Comment by pablolh** [comment]
Thanks, updated the changelog.

**Review by wvlothuizen — APPROVED** [review]

**Comment by pablolh** [comment]
I don't seem to have the rights to merge this either. I don't see a "Merge" button.
@jvansomeren you could also take a look if you want

**Pull request merged**
