### PR TITLE
Enh/mapperdoc 294

### PR DESCRIPTION
**Pull request by jvansomeren**
The user documentation of the router/mapper has been written.
It details options and related functionality,
and describes which parts of the configuration file are used by the mapper.

What needs to be done:
- polishing 
- reviewing it

### CODE REVIEW

**Comment by imranashraf** [comment]
@jvansomeren merge develop into your branch for Travis CI to pass

**Comment by jvansomeren** [comment]
@imranashraf justed merged develop into branch but was surprised of the reaction:
```
[jvansomeren@hymir OpenQL]$ git status
# On branch enh/mapperdoc-294
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	.pytest_cache/
nothing added to commit but untracked files present (use "git add" to track)
[jvansomeren@hymir OpenQL]$ git merge develop
Already up-to-date.
[jvansomeren@hymir OpenQL]$ git push
Everything up-to-date
[jvansomeren@hymir OpenQL]$ 

```
How can I test whether the tests now pass?

**Comment by jvansomeren** [comment]
@imranashraf got it probably: it certainly helped to first checkout develop, pull it, and then checkout enh/mapperdoc-294 and merge develop into it.
Its reactions were what I expected and at this moment I see above that CI building is in progress.

**Comment by jvansomeren** [comment]
@imranashraf but it still fails in CI

**Comment by jvansomeren** [comment]
The changes of today are mostly concerned with how gate names are written, as in `swap`.
Furthermore to consistently write names of fields, sections and gates in `type-writer` font,
and to write new important terms in _italic_ font.

However, the Travis CI tests are still failing. This is not a reason not to merge.

The text has been read, is consistent now, and spelling errors have been largely corrected.

**Comment by jvansomeren** [comment]
Also Hossein is reading the text.
Please wait with merging this pull request until he has done his reading.

**Comment by imranashraf** [comment]
@hasali92 why did you force pushed to develop??????

**Comment by hasali92** [comment]
I didn’t, maybe someone else using my account. Who is this?
________________________________

**Comment by imranashraf** [comment]
This is wierd. I cannot understand how can someone else do this on your behalf, unless your account is hacked !!!

**Comment by hasali92** [comment]
Multiple people are using the same setup and GitHub accounts are opened already, thus they use them. I wonder who I am talking to.
________________________________

**Comment by imranashraf** [comment]
Imran Ashraf, QCA Lab. May I know who are you?

**Comment by hasali92** [comment]
Hany Ali, LDC lab.
________________________________

**Comment by hasali92** [comment]
I will ask in the group who did that and feed you back.
________________________________

**Comment by MiguelSMoreira** [comment]
@imranashraf please check my personal email for clarification

**Comment by imranashraf** [comment]
fixed forced push issue and travis CI also working. merging for now to avoid further confusion. if required, re-create branch for mapper documentation

**Comment by jvansomeren** [comment]
Hi Imran,

When doing openql.readthedocs.io<http://openql.readthedocs.io> I don’t see the mapper documentation.
Did I do something wrong or need readthedocs to be synced somehow?

Best,

Hans

Op 30 mrt. 2020, om 13:10 heeft Imran Ashraf <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Merged #301<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QE-2DLab_OpenQL_pull_301&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=wpQg0i0BZ3VjL8EFTTX5lEB7LV3HW-OpTXJcX-MWvIs&s=7AZMVbTi57XpoJBa5ZjrLq8wS-ldRREJJf5oBT9IYLA&e=> into develop.

**Comment by imranashraf** [comment]
@jvansomeren this is because documentation build is failing.

**Comment by jvansomeren** [comment]
Do you know why?
Can I solve it?

Groet,

Hans van Someren

atelier GROENBLAUW
Koningsplein 93<x-apple-data-detectors://1/0>
2611 XG Delft<x-apple-data-detectors://1/0>
06 4298 2220<tel:06%204298%202220>

hans@ateliergroenblauw.nl<mailto:hans@ateliergroenblauw.nl>

www.ateliergroenblauw.nl<http://www.ateliergroenblauw.nl/>
www.groenblauwenetwerken.com<http://www.groenblauwenetwerken.com/>
www.huisjeboompjebeter.nl<http://www.huisjeboompjebeter.nl/>





Op 12 apr. 2020 om 04:59 heeft Imran Ashraf <notifications@github.com> het volgende geschreven:

﻿

@jvansomeren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jvansomeren&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=aWVOK53iwlQrzL_QcF-RhCzE39TDdhNA6MnyFNGha5A&s=yZ0TwLVCroUvVBKG12qbMlgui12g9Kpfo0f3JgTrpoI&e=> this is because documentation build is failing.

**Comment by imranashraf** [comment]
this is because readthedocs build system cannot build the documentation due to missing packages.

if you want you can setup readthedocs account and link it with openql project to have a look at the details and fix it.

**Pull request merged**
