### PR TITLE
CPP example compilation

### PR DESCRIPTION
**Pull request by imranashraf**
updated cmake files to sucessfully build cpp example **simple.cc**.

also added a standalone example to compile cpp examples outside openql directory, if required.

This should fix https://github.com/QE-Lab/OpenQL/issues/245.

### CODE REVIEW

**Comment by imranashraf** [comment]
@jvansomeren could you test it?

**Comment by jvansomeren** [comment]
Hi Imran,
No, didnt have time
Was documenting
Perhaps next Monday I’ll try

Groet,

Hans

Op 11 dec. 2019 om 12:46 heeft Imran Ashraf <notifications@github.com> het volgende geschreven:

﻿

@jvansomeren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jvansomeren&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=kNTuyNQOvr2rXDPtsTREszY1ml4U2jrRSw1khGpDjRI&s=Y5yeyhV43Nr7ZpRPAjaHcMUve_AAuMpDHa5-kbipZ-8&e=> could you test it?

**Comment by jvansomeren** [comment]
Hi Imran,
I'm trying to integrate this but failed because I don't understand the changes.
Suppose in tests, there is a test_mapper.cc which looks like:

#include <openql_i.h>

int main(int argc, char ** argv)
{
    ql::utils::logger::set_log_level("LOG_NOTHING");
}

And I update CMakeLists.txt to contain the lines:

ADD_EXECUTABLE(test_mapper test_mapper.cc )
TARGET_LINK_LIBRARIES(test_mapper ${LEMON_LIBRARIES} )

What do I then have to update to get this compiled?

Best,

Hans

**Comment by jvansomeren** [comment]
I created the cpp-example branch to track origin/cpp-example
and went into it to the standalone example.
I updated the OPENQL_ROOT to be /home/jvansomeren/ql/OpenQL
But I don't know what to do with the next line, the one with _openql.so.
Also, should I create a cbuild, and where? And where should I call cmake, and how?
When I created a local cbuild directory and after cd cbuild, do cmake ..,
this fails with: *** No rule to make target '/home/jvansomeren/ql/OpenQL/cbuild/swig/_openql.so', needed by 'example'.

**Comment by imranashraf** [comment]
I copied simple.cc to tests as test_mapper.cc

I added the following two lines to tests/CMakeLists.txt

```
ADD_EXECUTABLE(test_mapper test_mapper.cc )
TARGET_LINK_LIBRARIES(test_mapper ${LEMON_LIBRARIES} ql)
```

then you can run the following as mentioned in [openql documentation](https://openql.readthedocs.io/en/latest/installation.html#linux-osx)
```
mkdir cbuild
cd cbuild
cmake ..
make
```

to generate the test_mapper executable. I hope its clear now.

Right now you can pull this branch and start populating test_mapper.cc with your tests.

**Comment by jvansomeren** [comment]
Hi Imran,
Thanks!
I added lines setting loglevel and an option and it links well, without errors.
I propose you merge this pull request into develop and close the issue.
I can then proceed merging develop into mapper.
Best,
Hans

**Pull request merged**
